sudo: false

install:
- ./gradlew assemble --stacktrace

script:
- set -e
- source build/release/gradle/setGitVariables.sh
- ./gradlew release -Prelease.disableRemoteCheck -Prelease.localOnly --stacktrace --continue
- ./gradlew check publishToMavenLocal -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_API_KEY} --stacktrace --continue
- ./gradlew finalizeRelease publishUploadedArtifacts -x test -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_API_KEY} --stacktrace

language: groovy

jdk:
- oraclejdk8

env:
  global:
  - SKIP_RELEASE=true
  - secure: Pz5Il8x0CxyQzwG/xwqexN38yMXjiHAuxCeJN6l8ZLHwf0ex8xNc9fh4X9WjrDZJBVi16w/biev50dvuau1fh1WFOYVrNsay+yS8lEhDbdA2gHTIKFrSB8NST5GsyS5yYuj8Hblxu5eMM7oo7cHk9WJovYiNb8mDnzVEKO6uNV7wKM3Vd6mnBsFmvmyGj+ZHxUk5K2jeCrXSMMFiWbXHqfqb/pp+awqtEWPHpDYf1QPmFZyBT4k5eHWWIrbavnMoYrHVrA7j6YZpBzeavW6avOUiHRdO34WBS++7LyYiOueLq8yaAGhWzUvDSRemXiO/SQVVQE3HlAXiMtvuztx04QNgN7KYbHbcTQlBtu+yIDlC45nQMjp11IfBj9SSGtE7oqbVDjn1ngHVfL2/+AW51/d0Dp5EdVZxp2tAIni2p6HqLg034HgQHMqSVvu3+1uQj4AiJJr7uHH1BxNh8WltX0ASjd6hbQqE+T9LXcVMg9OXnMlxKhwa3DIoWuVqQmviUqQ0aeoLcV3N8HHjCgKaKtQD58GlhETo7myXlK8s5DedoLtZPQ5gCsizBh1MkrVmDOwctMXX36+gYIEmb/xD84XdTkOZR1l0IXNeeOxhx9f5r1gXw6PW9ClnewSXG1D5Yv/mAkasIMKgSKE3PupRHjmS8x8+iWtTfbRVUprH4L4=
  - secure: FiPdtRE3FVC061+Rkrv7qz4Jnu+r0XoZHYDDpdFa6FAofknMVIxTRJharRHjpk+iD8vE8lH0Yo+yuXRVQPpzyFoNZWLoPfDOxpX8+leS3sZ7PRIXbaIyFpqKwjcO37+bkW89NEpYrjTK3cSewYdhEa8SY1mKhvmFiHWmO6UVDgOJWkmbF31xYqNefh/g4QbhPpXThd4McT6eOiiJEwHkOn1T/FGJPmO5JtTOc22TkwhM7uf47v3o9WR5zbccc2VOCHPZ1gH2TqmvTTZ/oXcXm6/74vNU2NvMFk4dIGrL4hK6wK+daWccp10dlEUkGnfErrGQLbcTQyxp9/uQNIxa/ysel+YEWpN1kxarREajPWY26Q5j60+Sdh+KnY5Pfcl89rvtU2Q2LCW3WR1AGMeaZpRhS8VEfNVU8Y779V4ZpijZxJuvXU1GN3A6mjNvncwAVSH08JZt2I1A7UcXZz5fDNjXYxNZ6qK2sNF+uYYWhvgBGS48a4YuVlb7tbpMjt+f0VzAJRCUTA3QwNzXskHeTW6PIahlpJzK61kCd0XuP2m9A3meOYlHUVc+nxV14QSunBoNGPBQDZPLicChFkPVRzs/XYYAU3nF3HcKI2T3U2+kOaVfXBdvjpsRRrNVV+2nwcENwyUv4EfpFEzITS568Wrus9BnCwlBN6Z/cs190HE=
  - secure: A+LHxmQqOHBf5wRv9CNaS3nMGsXG9rM0MzL7asdvMc/mlj5JvbuYkkQg48j5u/HNP/lNB/v7jb1PYQXjpxaQzfdP6Cw5EGgtnORU9ou8Qq9l36TlrzeQCfamij38OsMnyW8FEqJV351Zexplmgw80LYH6UVvxadzCNvQIevSnDgPkgYsdU5h4ZxByauZMzg0VMo+ffvU3COds3hKx2G+83+2ci/HOZHNz7DZ07iU6DdCHXQhwwnKj3LWDzJ/7cPEX4+yJjlX/YA8o8S8f6cSMOpWa1U7aJF4zgZ3hj3pDAz9nP4GbU/yY8NFWofqzmGLQ6XuCncEitKXQcrJVLuOsNcioE+WDNE4+i0ynf3Fl34zYzEch2anzTbrCyxfrg8ARgtDf12Wf/cpJyxQgPJM/ALXId0Y8G2l7v5TZsLDc5U3xE/ggu2NLIUHV/XxvnsTxU3L7jEdbbVcSefpuKTimdqWSMrCaqwwKCaQGnK790zkXDKw4rdoAp+ieCGOMa/vVigLiqnwJuKeyiZHLZskJwuEAxgi17yh6Dpfo1Nwa08bTlIel/tlk/U+5BZlyHGJOqjg3FxMGEOH0xAHX4B+S2+cSsNKnZVdvVH4VSwAVPo+5fXT7q+Y3lKMKkjmLyyNm15YHL9UzzMJkLVItKPgFoN32wS5T5BpviGb52xjL90=
