sudo: false

install:
- ./gradlew assemble --stacktrace

script:
- set -e
- source build/release/gradle/setGitVariables.sh
- ./gradlew release -Prelease.disableRemoteCheck -Prelease.localOnly --stacktrace --continue
- ./gradlew check publishToMavenLocal -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_API_KEY} --stacktrace --continue
- ./gradlew finalizeRelease publishUploadedArtifacts -x test -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_API_KEY} --stacktrace

language: groovy

jdk:
- oraclejdk8

env:
  global:
  - SKIP_RELEASE=false
  - secure: ArhMI+wH8zs6H0+F+wNQpRKVhM/mppekik1h8XytcCri4KHPI6UGup4ECwdVfNvJN1H8I2WqEpzgkpt2UXidCTe2qUsWwxtvZUGbZq5ru9gyGt2fY80npQE0Wtw5e+bNkFFEubsR5wvd4gSBI0RQx5SFqWDtgYP2Nv8jkxHimD/iQ7HhCYEKSCyJIRB/HCpADcVpIxng8tWWE3xTtyXTofJZxFkbG9o6dInyGIsj+r6egqln0VyKK+DSI6xUOeBALuDzKv/w0E2Z8dWYDSW90ABeGA4bFDSoqyg+N6KePpoSCetFWyje2RQk2NgFwt0aMJq13XRW3P1ARIyQVO56YtBWPwd0L0fs50mqOOdc1gz535P4gl/rbTz8LFU6Ro9Xmc8+4bFddmBPGO3FUVAnpV9vkP5ekAy8fHmXwpJzy1sovnH9i1UAA3NsNH3VaO109qYhd5cXtigidRzjhytjfKahUhFSjm19cPKJcukbr0LJsHCed9xJ4rUH9Qni82WpxjPSmzrW5RPjECCjJcfcLUlDsnc1nwNUr3bhbPvjLcfHIvEBdmf9e8erqvgLH7eGl4n/BiIQpDu8bu4R8vjBXrFVKN84m0H+5KKYtfjVRH3b804VwBrF8ZaSV0hTPQMsb37f/+sM4oUVW9pZ+G4F83QXzN3+7XBDS+RGgIifC/Y=
  - secure: FiPdtRE3FVC061+Rkrv7qz4Jnu+r0XoZHYDDpdFa6FAofknMVIxTRJharRHjpk+iD8vE8lH0Yo+yuXRVQPpzyFoNZWLoPfDOxpX8+leS3sZ7PRIXbaIyFpqKwjcO37+bkW89NEpYrjTK3cSewYdhEa8SY1mKhvmFiHWmO6UVDgOJWkmbF31xYqNefh/g4QbhPpXThd4McT6eOiiJEwHkOn1T/FGJPmO5JtTOc22TkwhM7uf47v3o9WR5zbccc2VOCHPZ1gH2TqmvTTZ/oXcXm6/74vNU2NvMFk4dIGrL4hK6wK+daWccp10dlEUkGnfErrGQLbcTQyxp9/uQNIxa/ysel+YEWpN1kxarREajPWY26Q5j60+Sdh+KnY5Pfcl89rvtU2Q2LCW3WR1AGMeaZpRhS8VEfNVU8Y779V4ZpijZxJuvXU1GN3A6mjNvncwAVSH08JZt2I1A7UcXZz5fDNjXYxNZ6qK2sNF+uYYWhvgBGS48a4YuVlb7tbpMjt+f0VzAJRCUTA3QwNzXskHeTW6PIahlpJzK61kCd0XuP2m9A3meOYlHUVc+nxV14QSunBoNGPBQDZPLicChFkPVRzs/XYYAU3nF3HcKI2T3U2+kOaVfXBdvjpsRRrNVV+2nwcENwyUv4EfpFEzITS568Wrus9BnCwlBN6Z/cs190HE=
  - secure: A+LHxmQqOHBf5wRv9CNaS3nMGsXG9rM0MzL7asdvMc/mlj5JvbuYkkQg48j5u/HNP/lNB/v7jb1PYQXjpxaQzfdP6Cw5EGgtnORU9ou8Qq9l36TlrzeQCfamij38OsMnyW8FEqJV351Zexplmgw80LYH6UVvxadzCNvQIevSnDgPkgYsdU5h4ZxByauZMzg0VMo+ffvU3COds3hKx2G+83+2ci/HOZHNz7DZ07iU6DdCHXQhwwnKj3LWDzJ/7cPEX4+yJjlX/YA8o8S8f6cSMOpWa1U7aJF4zgZ3hj3pDAz9nP4GbU/yY8NFWofqzmGLQ6XuCncEitKXQcrJVLuOsNcioE+WDNE4+i0ynf3Fl34zYzEch2anzTbrCyxfrg8ARgtDf12Wf/cpJyxQgPJM/ALXId0Y8G2l7v5TZsLDc5U3xE/ggu2NLIUHV/XxvnsTxU3L7jEdbbVcSefpuKTimdqWSMrCaqwwKCaQGnK790zkXDKw4rdoAp+ieCGOMa/vVigLiqnwJuKeyiZHLZskJwuEAxgi17yh6Dpfo1Nwa08bTlIel/tlk/U+5BZlyHGJOqjg3FxMGEOH0xAHX4B+S2+cSsNKnZVdvVH4VSwAVPo+5fXT7q+Y3lKMKkjmLyyNm15YHL9UzzMJkLVItKPgFoN32wS5T5BpviGb52xjL90=
